import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const font = localFont({
  src: [
    {
      path: "../public/fonts/circular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/circular-medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/circular-bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  display: "swap", // Optional, controls how the font is displayed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
