import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Outfit } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
const font = Outfit({
  subsets: ["latin"],
  weight: ["400"],
});

// const font = localFont({
//   src: [
//     {
//       path: "../public/fonts/Gilroy-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Gilroy-Bold.ttf",
//       weight: "700",
//       style: "bold",
//     },
//   ],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Toaster richColors position="top-right" /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
