export const PRODUCT_CATEGORIES: Readonly<[string, ...string[]]> = [
  "Electronics",
  "Fashion",
  "Home & Garden",
  "Beauty & Personal Care",
  "Toys & Games",
  "Sports & Outdoors",
  "Automotive",
  "Health & Wellness",
  "Books, Movies & Music",
  "Office Supplies",
  "Pet Supplies",
  "Jewelry & Accessories",
  "Grocery & Gourmet Food",
  "Baby Products",
  "Tools & Home Improvement",
  "Furniture",
  "Party Supplies",
  "Watches",
  "Luggage & Bags",
  "Art & Craft Supplies",
];
